languageCode = "en-us"
title = "agileVigo"
baseurl = "https://www.agilevigo.com/"
theme = "aerial"

[params]
  name_1 = "agile"
  name_2 = "Vigo"
  about = "Meetup de agile en la ciudad de Vigo."
  copyright = ""
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/agilevigo"

[[params.social]]
  medium = "Meetup"
  icon = "meetup"
  link = "https://www.meetup.com/es-ES/agile-vigo/"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/agileVigo"
